#!/usr/bin/env bash
set -e

case "$1" in
  dev)
    ./scripts/dev.sh
    ;;
  prod)
    ./scripts/prod.sh
    ;;
  stop)
    ./scripts/stop.sh
    ;;
  status)
    ./scripts/status.sh
    ;;
  *)
    echo "Usage: ./mode {dev|prod|stop|status}"
    exit 1
    ;;
esac
